name: Update Dependencies on Pull Request

on:
  pull_request:
    branches:
      - main  # or any other branch you'd like to monitor

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (for sbt)
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or adopt, zulu, etc.
          java-version: '8'

      # Step 3: Cache sbt dependencies (optional but speeds up the build)
      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Step 4: Run sbt command to update dependencies file
      - name: Run sbt writeDependencies
        run: sbt writeDependencies

      # Step 5: Check if the dependencies file was changed
      - name: Check for changes
        run: git diff --exit-code || echo "Dependencies file has changed"

      # Step 6: Commit and push changes if necessary
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dependencies via sbt writeDependencies
